### ISSUE TITLE
RegistrantNotRegisteredError in Tiger-Hooknet Example

### ISSUE THREAD

**Issue by AmartyaCSB** [DIAGNijmegen/pathology-whole-slide-data#14]
Hi, Thanks a lot for this tool!
I am trying to run the notebook Tiger - HookNet training.
I have set up python 3.8.5 and on RHEL server/Windows machine.

I am encountering this error: 
```
RegistrantNotRegisteredError: 
        Registrant 'openslide' is not found in the register of class 'WholeSlideImageBackend' with an empty register
```
when I try to create the create_batch_iterator
I have openslide-python installed already.

Could you please help me in fixing this issue? It comes up in RHEL servers, windows machines.

**Comment by martvanrijthoven** [comment]
Dear Amartya Mandal,

Thanks for your interest in this package.

Wholeslidedata supports three image backends: openslide, ASAP, and pyvips. You will have to install additional software for these backends. You will only need one.

For openslide please see installation instructions [here](https://openslide.org/download/)
For ASAP please see installation  instructions [here](https://github.com/computationalpathologygroup/ASAP/releases/tag/ASAP-2.0-(Nightly))
for pyvips please see installation instructions [here](https://anaconda.org/conda-forge/pyvips)

You can easily switch between different image backends in the config file. The options are 'openslide', 'asap' and 'pyvips'

For example:
wholelslidedata:
	image_backend: asap

openslide is currently the default image backend.

Please let me know if you run into a problem while installing openslide, ASAP, or pyvips.


Best wishes,
Mart
