### ISSUE TITLE
Tissue masking

### ISSUE THREAD

**Issue by michelbotros** [DIAGNijmegen/pathology-whole-slide-data#26]
Hi Mart,

I was wondering if there is anything available yet for tissue masking. I think there is quite some use cases for tissue masking.
For example:

1.  When working with WSI's without annotations. Still being able to sample patches from tissue regions from the WSI would be a nice to have.
2. To exclude annotations that are outside of tissue regions. In my project I'm dealing with ''lazy annotations'' where at the border of the biopsy some non tissue is often included in the annotated region to save time during the annotation process (see example below).

It might be beneficial to perform tissue masking before patch extraction for the first use case. Let me know what you think and if there is already options for this!

Best,

Michel

**Comment by michelbotros** [comment]
![example_lazy_annotations_3](https://user-images.githubusercontent.com/4972463/169791726-ecd0917c-a5fe-42b5-9ae8-6abd68fe8862.png)

**Comment by martvanrijthoven** [comment]
Dear Michel,

There are two options available already. 

The first one is by using the [MaskAnnotationParser](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0090eb2cfb131a0227858db791ad999651313bcd/wholeslidedata/annotation/parser.py#L167)
This parser converts a mask into multiple rectangle regions for which the size can be specified. 

Another option, which I would recommend, is to create polygons from the tissue mask with this [function](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0090eb2cfb131a0227858db791ad999651313bcd/wholeslidedata/annotation/utils.py#L83)
With the Shapely library, you can intersect the tissue mask polygons and the annotated polygons. From the intersection you create a new annotation file, e.g., with [write_asap_annotation](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0090eb2cfb131a0227858db791ad999651313bcd/wholeslidedata/accessories/asap/annotationwriter.py#L138) or use the internal JSON representation of wholeslidedata [convert_annotations_to_json](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0090eb2cfb131a0227858db791ad999651313bcd/wholeslidedata/annotation/utils.py#L162). In this way you get a cleaned annotation file which you can use for training.

I hope this helps and please let me know if anything is unclear.

Best wishes,
Mart

**Comment by michelbotros** [comment]
Dear Mart,

Thanks for the suggestions. I think the second option, where a clean annotation file is created, is indeed preferred. If I understand it correctly we then find the intersection between the tissue region and the annotation region on polygon level. 

This [function ](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0090eb2cfb131a0227858db791ad999651313bcd/wholeslidedata/annotation/utils.py#L83) converts a tissue mask (Numpy) to polygon format and assumes that I have already obtained a tissue mask as well, right? What would you recommend to obtain the tissue masks themselves?

Best,

Michel

**Comment by martvanrijthoven** [comment]
Hi Michel,

Yes, indeed the intersection can then be done on polygon level. And yes you can use that function to convert a NumPy array to polygons. You can use a spacing value of ~4.0 or ~8.0 when opening the mask (please use the asap backend, because openslide backend does not work well with monochrome images) and upscale the polygons.

For creating tissue masks I recommend using this [algorithm](https://grand-challenge.org/algorithms/tissue-background-segmenation/)

Best wishes,
Mart

**Comment by michelbotros** [comment]
Hi Mart,

Okay, all clear! Thank you very much for the explanation.

Best,

Michel

**Comment by michelbotros** [comment]
Hi Mart,

I requested access to the [algorithm](https://grand-challenge.org/algorithms/tissue-background-segmenation/) that you mentioned, but its still pending. Do you perhaps know who I would have to contact to get permission?

Best,

Michel

**Comment by martvanrijthoven** [comment]
Hi Michel,

If it is still pending, maybe you can contact [Peter Bandi](https://www.aiosyn.com/team/#peter-bandi) he has created this algorithm.
