### ISSUE TITLE
I got confused between branch 'main' and '0.0.16'

### ISSUE THREAD

**Issue by BestVIncent** [DIAGNijmegen/pathology-whole-slide-data#34]
When I use your project 'pathology-hooknet', there are many import issuses from wholeslidedata.
For example, if I install wholeslidedata package with branch 'v0.0.16', the notebook in hooknet will report missing 'wholeslidedata/visualization'. But it does exist in branch 'main'. So I install wholeslidedata with branch 'main' instead, and it will report missing some functions in 'wholeslidedata/samplers/utils.py'.
Maybe notebooks in hooknet have been outdate. I don't know how to fix it.

**Comment by martvanrijthoven** [comment]
Dear BestVincent,

Thank you for this issue report. Currently, wholeslidedata is transitioning to 0.1.0 (main branch), and indeed there were some incompatible issues  with [HookNetPracticalGuide.ipynb](https://github.com/DIAGNijmegen/pathology-hooknet/blob/master/notebooks/HookNetPracticalGuide.ipynb). I have fixed this now and the notebook should work again if you install wholeslidedata from the main branch:
```bash
pip install git+https://github.com/DIAGNijmegen/pathology-whole-slide-data@main
```
Sorry for the inconvenience. Please let me know if you run into more issues.

Best wishes,
Mart
