### ISSUE TITLE
from wholeslidedata.source.configuration.config import insert_paths_into_config

### ISSUE THREAD

**Issue by ZhangRan24** [DIAGNijmegen/pathology-whole-slide-data#40]
from wholeslidedata.source.configuration.config import insert_paths_into_config
       ModuleNotFoundError: No module named 'wholeslidedata.source'

I can't find the insert_paths_into_config, I really hope to receive a reply. Thank you

**Comment by martvanrijthoven** [comment]
Dear ZhangRan24,

Thank you for this issue! Could you please let me know how you installed wholeslidedata and where you have found the import line?

Best wishes,
Mart

**Comment by martvanrijthoven** [comment]
The insert_paths_into_config function is depreciated but if you still need it, please consider to install wholeslidedata==0.0.16

If you still run into problems, please let know.

Best wishes
