### ISSUE TITLE
QuPath annotations (.geojson) format not readable by parser

### ISSUE THREAD

**Issue by tsikup** [DIAGNijmegen/pathology-whole-slide-data#41]
The '.geojson' annotation files that QuPath exports are not readable by the annotation parser.
This is due to the different structure of '.geojson' and the implemented parser of '.json' files.
I will be submitting a fix soon.

**Comment by martvanrijthoven** [comment]
Dear Nikos Tsiknakis

Thank you for this issue. Indeed the current qupath annotation parser in v0.16.0 might follow a different structure (it was based on a custom export script that i made a while ago). If you can implement a correct parser that would be great!
If it is possible please implement it for wholeslidedata==v0.1.0 version (which is now on the main branch but not on pypi yet). I actually noticed that in the main branch the qupath parser is empty: https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/wholeslidedata/interoperability/qupath/parser.py

It would be amazing if you could create a PR for a correct parser for qupath export!

Best wishes,
Mart
