### ISSUE TITLE
Patch label sampler fails with point annotation

### ISSUE THREAD

**Issue by JoeySpronck** [DIAGNijmegen/pathology-whole-slide-data#45]
I was sampling patches that I used to sample correctly with WSD 0.15/0.16

However I got the following error: 
IndexError: index 1 is out of bounds for axis 0 with size 1

at this line:
https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/0a20034f237ed154f0d74f75bbd15432c80ddcc3/wholeslidedata/samplers/patchlabelsampler.py#L146

Aparantly there is an incorrect point annotation (a TIL) in a segmentation class (stoma) that im sampling, but this didnt fail before, and I think it shouldnt fail

'coordinates' in this case = [[99.7655 78.5625]]

so I think uit should be:
mask[int(coordinates[0][1]), int(coordinates[0][0])]
instead of:
mask[int(coordinates[1]), int(coordinates[0])]

**Comment by JoeySpronck** [comment]
Just tested it and it indeed solves the issue

**Comment by martvanrijthoven** [comment]
Thanks Joey, could you please make a PR for this fix?

**Comment by martvanrijthoven** [comment]
Thanks Joey!!

Fix by Joey #46
