### ISSUE TITLE
mask to xml/json overhaul

### ISSUE THREAD

**Issue by JoeySpronck** [DIAGNijmegen/pathology-whole-slide-data#48]
In the current version of WSD there are many bugs in the code to make XMLs from masks.

I made many improvements and rewrote functions. Im not sure though how you would like merge the changes. Im not sure if all these changes will break other code, therefore, I'll make a PR with all changes in a single script that converts masks to xml/json, so you can check everything easily in that single file.

**Comment by martvanrijthoven** [comment]
Thanks Joey, sorry for my late response. For me fine to merge as is
